### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haltode** [prologin/gcc-resources#11]
As discussed in https://github.com/prologin/gcc-resources/pull/7#discussion_r358918562 we should add a license to re-use/modify/share the practicals.

I am proposing the following license: https://creativecommons.org/licenses/by-nc-sa/4.0/

We might discuss the "non-commerical" aspect of the license.

**Comment by Elfikurr** [comment]
The only thing with the "non-commercial" part is that it should be possible for someone (a company or a person) to buy the right to use our resources for a commercial purpose ?
Like sell our work ?
I'm not saying we can, I'm saying, would we ever want to do that ?
(It implies some other stuff, such as the non-profit part, the restricted access for our content etc., so we would need to discuss this)
