### ISSUE TITLE
Web: href instead of src

### ISSUE THREAD

**Issue by Gabzcr** [prologin/gcc-resources#29]
`<link rel="stylesheet" src="css/style.css">`

In the Web TD, this line explaining how to put some css code in our html file contains an error. It should be `href` instead of `src`.

**Comment by Gabzcr** [comment]
Also, in the css file : 
`figcaption {
  color: \#FF0000;
}`
The `\` should not be here. The color won't change when it is here.

**Comment by pguenezan** [comment]
Up

**Comment by alarsyo** [comment]
fixed in 4a99ca720f58217d19ec8675528808bb17e7e742, but the `gh-pages` deployment branch hasn't been updated since then.
